server:
  port: 8081

spring:
  application:
    name: user-service

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_user_db
    username: postgres
    password: ha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# JWT configuration
jwt:
  secret: Pma6hMA+QdiVA4lwmxzHtJszfcf5pYxj8KvdNYvP6+4= # Base64 encoded secret key
  expiration: 3600000 # 1 hour in milliseconds
  refresh-expiration: 2592000000 # 30 days in milliseconds
