server:
  port: 8081

spring:
  application:
    name: user-service

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_user_db
    username: postgres
    password: ha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/