server:
  port: 8080

spring:
  application:
    name: api-gateway

  # Spring Cloud Gateway configuration
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/users
            - id: user-service-auth
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/auth

# eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/