server:
  port: 8080

spring:
  application:
    name: api-gateway

  # Spring Cloud Gateway configuration
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-auth
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/auth
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuitBreaker
                    fallbackUri: forward:/fallback/users

# eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

# JWT Configuration
jwt:
  secret: Pma6hMA+QdiVA4lwmxzHtJszfcf5pYxj8KvdNYvP6+4=
  expiration: 3600000 # 1 hour in milliseconds
  refresh-expiration: 86400000 # 24 hours in milliseconds

# Cors Configuration
app:
  cors:
    allowedOrigins:
      - http://localhost:3000
      - http://localhost:4200

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.ha.apigateway: DEBUG