server:
  port: 8082

spring:
  application:
    name: game-service

  # MongoDB configuration
  data:
    mongodb:
      database: game_service_db
      host: localhost
      port: 27017
      # username: your_username
      # password: your_password
      # authentication-database: admin

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Logging configuration
logging:
  level:
    org.ha.gameservice: DEBUG
    org.springframework.data.mongodb: DEBUG
